### ISSUE TITLE
Output filter parser's regex doesn't handle directories with a dot/period character in their name

### ISSUE THREAD

**Issue by osarup** [RHESSys/RHESSys#162]
In `rhessys/output_filter/parser/output_filter_parser.l`, line 50, the regex that handles the output directory is:
`\"(\.{1,2}\/){0,1}(\/*[a-zA-Z0-9_\-\(\)\[\]])+\/*\" { yylval.string = strdup(yytext); return PATH_SPEC; }`

This does not handle paths such as `"/Users/Shared/work.flamenco/Projects/GordonGulch/calibration/sens_testing3"` due to the existence of  directory names like `work.flamenco`. For example:
```
filter:
  timestep: daily
  output:
    format: csv
    path: "/Users/Shared/work.flamenco/Projects/GordonGulch/calibration/sens_testing4"
    filename: "patch_daily"
  patch:
    ids: 1:28:11687:1168701
    variables: evap_total=evaporation+evaporation_surf, etc, etc
```

This will lead to errors such as:
```
"Error: syntax error, unexpected '/', expecting PATH_SPEC or FILENAME_SPEC, for token: |/|
construct_output_filter failed with error: output_filter_parser returned with an error.
```

However, this works correctly:
```
filter:
  timestep: daily
  output:
    format: csv
    path: "../calibration/sens_testing4"
    filename: "patch_daily"
  patch:
    ids: 1:28:11687:1168701
    variables: evap_total=evaporation+evaporation_surf, etc, etc
```

The fix should be to use the regex expression `\"(\.{1,2}\/){0,1}(\/*[a-zA-Z0-9_\-\(\)\[\]\.])+\/*\"`  that includes `\.` The resulting line would thus be:
`\"(\.{1,2}\/){0,1}(\/*[a-zA-Z0-9_\-\(\)\[\]\.])+\/*\" { yylval.string = strdup(yytext); return PATH_SPEC; }`

This is correctly done in line 49  that handles FILENAME_SPEC.

Tested via https://regex101.com/
